image: node:16

definitions: 
  caches:
    haxe: ~/haxe

  steps:
    - step: &build-test
        runs-on: 
          - self.hosted
        name: Test
        caches:
          - haxe
        script:
          - yarn global add lix
          - lix download
          - lix run travix node

pipelines:
  default:
    - step: *build-test
  branches:
    master:
      - step: *build-test
      - step:
          runs-on: 
            - self.hosted
          name: Build and Deploy Playground
          caches:
            - haxe
          script:
            - yarn global add lix
            - lix download
            - haxe playground.hxml
            - git clone git@bitbucket.org:vantagefxcrm/vantagefxcrm.bitbucket.io.git
            - cd vantagefxcrm.bitbucket.io
            - ls -lah
            - mkdir -p $BITBUCKET_REPO_SLUG
            - cp ../bin/index.* $BITBUCKET_REPO_SLUG/
            - git add -A
            - git commit -m "Update search-syntax"
            - git push origin master