image: node:16

definitions: 
  caches:
    haxe: ~/haxe

  steps:
    - step: &build-test
        runs-on: 
          - self.hosted
        name: Test
        caches:
          - haxe
        script:
          - yarn global add lix
          - lix download
          - lix run travix node

pipelines:
  default:
    - step: *build-test
  branches:
    master:
      # - step: *build-test
      - parallel:
        - step:
            runs-on: 
              - self.hosted
            name: Build and Deploy Playground
            caches:
              - haxe
            script:
              - yarn global add lix
              - lix download
              - haxe playground.hxml
              - git clone git@bitbucket.org:vantagefxcrm/vantagefxcrm.bitbucket.io.git
              - cd vantagefxcrm.bitbucket.io
              - ls -lah
              - mkdir -p $BITBUCKET_REPO_SLUG
              - cp ../bin/index.* $BITBUCKET_REPO_SLUG/
              - >-
                if git diff --exit-code; then
                  echo "No updates"
                else
                  # Ideally the following git config should point to the one who triggered this pipeline
                  # see https://jira.atlassian.com/browse/BCLOUD-16711?focusedCommentId=2327119&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2327119
                  git config --global user.email "kevin.leung@vantagemarkets.com"
                  git config --global user.name "Kevin Leung"
              
                  git add -A
                  git commit -m "Update search-syntax"
                  git push origin master
                fi
        - step:
            runs-on: 
              - self.hosted
            name: Build and Deploy Maven
            caches:
              - haxe
              - maven
            script:
              - echo "47.75.161.8 maven.unicornfintech.com" >> /etc/hosts
              - yarn global add lix
              - lix download
              - apt update -qqy && apt install -qqy maven
              - ./mvnw deploy -s .mvn/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn